version: "3.9"
services:
  sa-postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini-project1-db
    ports:
      - '5432:5432'
    volumes:
      - sa-db:/var/lib/postgresql/data

  sa-keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak
    volumes:
      - ./keycloak/realms/export:/tmp/export
      - ./keycloak/realms/import:/opt/keycloak/data/import
    ports:
      - '9090:9090'
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=9090"

    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  sa-mini-project1-service:
    build: ../sa-mini-project1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - sa-postgres
      - sa-keycloak
    ports:
      - '8080:8080'

volumes:
  sa-db:
    driver: local