spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mini-project1-db
    username: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/sa-mini-project1-realm-dev
          jwk-set-uri: http://localhost:9090/realms/sa-mini-project1-realm-dev/protocol/openid-connect/certs