spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://sa-postgres:5432/mini-project1-db
    username: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://sa-keycloak:9090/realms/sa-mini-project1-realm-prod
          jwk-set-uri: http://sa-keycloak:9090/realms/sa-mini-project1-realm-prod/protocol/openid-connect/certs

keycloak:
  client-id: sa-mini-project1
  secret: VhUfOyLPK9j8HaxrlAwzfGRCW0Km6noM
  auth-url: http://sa-keycloak:9090/realms/sa-mini-project1-realm-prod/protocol/openid-connect/token