spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: sa-mini-project1
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mini-project1-db
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  main:
    allow-bean-definition-overriding: true


server:
  port: 0
