spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mini-project1-db
    username: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/sa-mini-project1-realm-dev
          jwk-set-uri: http://localhost:9090/realms/sa-mini-project1-realm-dev/protocol/openid-connect/certs

keycloak:
  client-id: sa-mini-project1
  secret: C8qGz2pWGLD7QC46K4ORCQ2Q7z6kYIFd
  auth-url: http://localhost:9090/realms/sa-mini-project1-realm-dev/protocol/openid-connect/token
